api_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol={stock}.BSE&outputsize=compact&apikey={api_key}&datatype=csv
api_key: demo
data_dir: ../../data/
db_params: ./config/database.ini
sql_path: ./sql
offline: False
uprsi: 68
lowrsi: 58
uphist: 1
lowhist: -1
