api_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={stock}.BSE&apikey=XSQOR70VDTX2C9AI&datatype=csv
data_dir: /home/abhishek/projects/stockdata/stock-analysis/data/
db_params: ./config/database.ini
sql_path: ./sql
offline: False