stocklist:
  - RELIANCE
  - TCS
  - HDFCBANK
  - INFY
  - HINDUNILVR
  - ICICIBANK
  - SBIN
  - BAJFINANCE
  - HDFC
  - LICI
  - BHARTIARTL
  - ADANITRANS
  - ITC
  - ATGL
  - KOTAKBANK
  - ADANIGREEN
  - ADANIENT
  - ASIANPAINT
  - DMART
  - MARUTI
  - BAJAJFINSV
  - LT
  - HCLTECH
  - WIPRO
  - AXISBANK
  - TITAN
  - SUNPHARMA
  - ULTRACEMCO
  - NESTLEIND
  - ADANIPORTS
  - ONGC
  - JSWSTEEL
  - POWERGRID
  - TATAMOTORS
  - NTPC
  - ADANIPOWER
  - PIDILITIND
  - TATASTEEL
  - COALINDIA
  - SBILIFE
  - HDFCLIFE
  - HINDZINC
  - TECHM
  - GRASIM
  - DABUR
  - IOC
  - SIEMENS
  - DIVISLAB
  - VEDL
  - HINDALCO
  - DLF
  - AWL
  - GODREJCP
  - EICHERMOT
  - SBICARD
  - BRITANNIA
  - LTI
  - INDUSINDBK
  - ICICIPRULI
  - HAVELLS
  - CIPLA
  - AMBUJACEM
  - SHREECEM
  - INDIGO
  - HAL
  - TATAPOWER
  - BPCL
  - SRF
  - TATACONSUM
  - BEL
  - DRREDDY
  - BERGEPAINT
  - VBL
  - MARICO
  - TATAELXSI
  - NYKAA
  - ICICIGI
  - CHOLAFIN
  - BANKBARODA
  - BAJAJHLDNG
  - APOLLOHOSP
  - ABB
  - GAIL
  - MOTHERSON
  - UPL
  - UNITDSPR
  - MINDTREE
  - HEROMOTOCO
  - NAUKRI
  - IRCTC
  - PAGEIND
  - LODHA
  - JSWENERGY
  - INDUSTOWER
  - ZOMATO
  - TORNTPHARM
  - BOSCHLTD
  - PIIND